"use client";
import type { Metadata } from "next";
import localFont from "next/font/local";
import ContextWrapper from "@/context/context";
import Header from '@/components/header';
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const plusJakartaSans = localFont({
  src: "./fonts/PlusJakartaSans-Regular.ttf",
  variable: "--font-jakarta",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${plusJakartaSans.variable} dark antialiased `}>
        <ContextWrapper>
          <Header/>
          {children}
        </ContextWrapper>
      </body>
    </html>
  );
}
