"use client";
import ContextWrapper from "@/context/context";
import Header from '@/components/header';
import "./globals.css";



// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`dark antialiased`}>
        <ContextWrapper>
          <Header/>
          {children}
        </ContextWrapper>
      </body>
    </html>
  );
}
